# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: box.paultibbetts.uk:587
mail_admin: wordpress@paultibbetts.uk
mail_hostname: paultibbetts.uk
mail_user: wordpress@paultibbetts.uk
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
