# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: vault_mysql_root_password

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: password

# Variables to accompany `group_vars/production/wordpress_sites.yml`
vault_wordpress_sites:
  paultibbetts.uk:
    env:
      db_password: example_db_password
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      # These CANNOT contain the characters "{%" in succession
      auth_key: "S?%H$}3{J:lSD)N_;-tW,:3tPTf>yt4PMd6C)=R/i|b~$<Tg&;sO(dnzbhDh~-<>"
      secure_auth_key: ";)DdDl5//I%$pU|ujoX_c9R_o/KG[DAp3akowME*fynD`]yC:,/3O-85FfpOAJif"
      logged_in_key: ";cF0Wj99lhjGxYijaa=8[S(ZODuvOp__EnwDWDqMT{XJTPK!LJq|Wds8nu_Xo)}I"
      nonce_key: "(6.$!(RqXg}hdZhck?29Q$]~@y^]Db<.OhC9D2QE6|n]6FaCUCeZ|DMcaNREQSjs"
      auth_salt: "Q>nWV)[k?%>dwYwbWZ^&=O[jv,bF2;jsFiQ@sKHP~(*fjz$M%/xFv&9MvtuQHQO{"
      secure_auth_salt: "5>/oxK_Q`sl3~fJkd(b{W6sD>vtwA9!!~,WH-%Ak.)UX*2JC$/}**.S8/Hl9MjV:"
      logged_in_salt: "2_emTfJECfRSCvK8]zAR(d75LHo-U@dzOz%_hOvP|WYf5kBnWYeQZr)vs-+.gOj)"
      nonce_salt: "-hj+_D>+.Fq^^iY1S).W6v_cHG|RWrR}^ +63IFhpOio;-(EWkBtHI_bJe4rQ1TL"
