# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  paultibbetts.uk:
    site_hosts:
      - paultibbetts.uk
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:ptibbetts/paultibbetts.uk.git
    branch: master
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo (above) if it is not the root (like the roots-example-project structure)
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: https://paultibbetts.uk
      wp_siteurl: https://paultibbetts.uk/wp
      wp_env: production
      db_name: pt_prod
      db_user: pt_dbuser
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
